<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{Introduction to pipeR}
-->

```{r, echo = FALSE, message = FALSE}
library(pipeR)
knitr::opts_chunk$set(
  comment = "#>",
  error = FALSE,
  tidy = FALSE)
```

# Introduction to pipeR

pipeR is a set of specialized, high-performance pipeline operators for R in attempt to make command chaining clear, fast, readable and flexible.

## Motivation

In data-driven statistical computing and analysis, applying a chain of commands is a frequent situation. Consider the following example.

Suppose we need to take these steps:

1. Generate 10000 random numbers from normal distribution with mean 10 and standard deviation 1
2. Take a sample of 100 without replacement from these numbers
3. Take a log of the sample
4. Take a difference of the log numbers
5. Plot these log differences with red line segments.

Here is the ordinary way we do this in R programming langauge:

```r
plot(diff(log(sample(rnorm(10000,mean=10,sd=1),size=100,replace=FALSE))),col="red",type="l")
```

The code is neither straightforward for reading nor flexible for modification. It is because the functions in the first few steps are hiding in the nested brackets, and the written order of the functions goes against the order of logic.

pipeR borrows the idea of F# pipeline operator which allows you to write the *object* first and *pipe* it to a following *function*. This package defines three binary pipe operators that provide different types of forward-piping mechanisms: first-argument piping (`%>>%`), free piping (`%:>%`), and lambda piping (`%|>%`). And the real magic of this kind of operators is chaining commands by the right order.
